# Generated by Django 5.2.7 on 2025-10-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visible',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends')], default='public', max_length=10),
        ),
    ]
